{% set version = "0.9.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-candisc
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/candisc_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/candisc/candisc_{{ version }}.tar.gz
  sha256: a488a51a2931c18d4541a67539892646b67d9d4d286995660e0d2c087a858572

build:
  number: 2
  noarch: generic

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]

  host:
    - r-base
    - r-car
    - r-heplots >=0.8_6

  run:
    - r-base
    - r-car
    - r-heplots >=0.8_6

test:
  commands:
    - $R -e "library('candisc')"           # [not win]
    - "\"%R%\" -e \"library('candisc')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=candisc
  license: GPL-2.0-or-later
  summary: Functions for computing and visualizing generalized canonical discriminant analyses and canonical correlation analysis for a multivariate linear model. Traditional canonical discriminant analysis is restricted to a one-way 'MANOVA' design and is equivalent to canonical correlation analysis between a set of quantitative
    response variables and a set of dummy variables coded from the factor variable. The 'candisc' package generalizes this to higher-way 'MANOVA' designs for all factors in a multivariate linear model, computing canonical scores and vectors for each term. The graphic functions provide low-rank (1D, 2D, 3D) visualizations
    of terms in an 'mlm' via the 'plot.candisc' and 'heplot.candisc' methods. Related plots are now provided for canonical correlation analysis when all predictors are quantitative.

  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
    - izahn
